services:
  postgres:
    image: postgres:16-alpine
    container_name: uwa_catalog_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uwa_catalog
    ports:
      - "5432:5432"
    volumes:
      - uwa_catalog_pgdata:/var/lib/postgresql/data

volumes:
  uwa_catalog_pgdata:
